apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Manually stop a component to reduce the quota utilization.
  name: stop
spec:
  appliesToWorkloads:
    - deployments.apps
    - statefulsets.apps
    - jobs.batch
    - cronjobs.batch
  podDisruptive: false
  schematic:
    cue:
      template: |
        if context.output.apiVersion == "apps/v1" && context.output.kind == "Deployment" {
          // +patchStrategy=retainKeys
          patch: spec: replicas: 0
        }
        if context.output.apiVersion == "apps/v1" && context.output.kind == "StatefulSet" {
          // +patchStrategy=retainKeys
          patch: spec: replicas: 0
        }
        if context.output.apiVersion == "batch/v1" && context.output.kind == "Job" {
          // +patchStrategy=retainKeys
          patch: spec: parallelism: 0
        }
        if context.output.apiVersion == "batch/v1" && context.output.kind == "CronJob" {
          // +patchStrategy=retainKeys
          patch: spec: suspend: true
        }
  status:
    customStatus: |-
      message: "component stopped"